import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Link href={"/"}>Home</Link>
      <br></br>
      <Link href={"/newTask"}>NewTask</Link>

      <body>{children}</body>
    </html>
  );
}
